### ISSUE TITLE
on linux, tn generate throws an error

### ISSUE THREAD

**Issue by vinzentt** [FokkeZB/tn#36]
Hi,

when trying tiny cli on my linux machine, tn generate outputs the following:
/usr/local/lib/node_modules/tn/lib/setup.js:101
      if (config.ios.devices && config.ios.devices.length > 0) {
                    ^
TypeError: Cannot read property 'devices' of undefined
    at process (/usr/local/lib/node_modules/tn/lib/setup.js:101:21)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/tn/lib/setup.js:173:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

It's not a big deal because tn generated the recipes for my android devices/emulators. 
Thanks for this great tool.

**Comment by FokkeZB** [comment]
@vinzentt could you try tn from master?

```
sudo npm i -g fokkezb/tn --unsafe-perm
```

**Comment by vinzentt** [comment]
no more error! Thx.
