### ISSUE TITLE
events.js:72

### ISSUE THREAD

**Issue by kopiro** [FokkeZB/tn#41]
```
$ tn r dev
TiNy cooked: appc run --platform ios --target device -V "XXXXXXXXX" -P XXXXXXXXXXXX --device-id all

execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
events.js:72
        throw er; // Unhandled 'error' event

```

**Comment by FokkeZB** [comment]
Do you have the `appc` CLI installed? If not, use `tn build` or `tn b` instead to use the `ti` CLI.

**Comment by kopiro** [comment]
Sorry, my mistake: `tn b dev` works, but `tn r dev` NOT.
