### ISSUE TITLE
On node 4.x, error

### ISSUE THREAD

**Issue by yomybaby** [FokkeZB/tn#46]
Hi Fokke,
`tn` is very useful. But I got an error, when  run `tn` on node 4.2.3.
( if I change node version to 0.12.x via `nvm`, it works properly)

```
/usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/build/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/build/Debug/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/build/Release/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/out/Debug/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/Debug/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/out/Release/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/Release/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/build/default/deasync.node
 → /usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/compiled/4.2.3/darwin/x64/deasync.node
    at bindings (/usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/tn/node_modules/appc-compat/node_modules/deasync/index.js:16:31)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tn/node_modules/appc-compat/lib/spawn.js:5:15)
    at Module._compile (module.js:435:26)
```

**Comment by yomybaby** [comment]
Oh! it works suddenly.
I don't know why. 

sorry for bothering

**Comment by FokkeZB** [comment]
Every time you switch major NodeJS version or in particular NodeJS version with a newer API version any modules that have native extensions must be rebuild. Reinstalling the module that has troubles is the easiest route. I hope NodeJS will come to handle this some day.
